### ISSUE TITLE
Not working after Batocera update

### ISSUE THREAD

**Issue by NeoZer01** [StarPlayrX/Virtual-Multi-Mouse#1]
Hello, I'm not able to get the VMM to work after an upgrade of Batocera on Raspberry PI 4  I've uninstalled and tried to reinstall but no luck getting it to work again.

I have spinner (Logitech) and a track ball (Happ).  It's only taking one or the other, not both.   

An interesting output, and the device that is having the issue is Happ trackball (usb-1241_1111-mouse)

 ./custom.sh start 5
[root@BATOCERA /userdata/system]# evsieve: no process found
While opening the device "/dev/input/by-id/usb-1241_1111-mouse":
    System error: failed to open a libevdev instance: /dev/input/by-id/usb-1241_1111-mouse.
Unknown device, --name=, --path=, or absolute path in /dev/ or /sys expected.
cat: /tmp/evmapy.txt: No such file or directory
0 Virtual_Multi_Mouse
1 usb-1241_1111-mouse
8 evmapy

**Comment by azsoccerpop** [comment]
same error on install: 

While opening the device "/dev/input/by-id/usb-Ultimarc_I-PAC_2_5-if01-mouse":
    System error: failed to open a libevdev instance: /dev/input/by-id/usb-Ultimarc_I-PAC_2_5-if01-mouse.
Unknown device, --name=, --path=, or absolute path in /dev/ or /sys expected.
0 Virtual_Multi_Mouse
3 usb-Ultimarc_I-PAC_2_5-if01-event-mouse
10 evmapy

**Comment by StarPlayrX** [comment]
What version of Batocera is this happening on?

**Comment by macOS26** [comment]
Development has been discontinued. 

I decided to move on to native emulators and the ones I am choose for my hardware natively supports mice. 

These emulators are Stella, MAME and BigPEmu.

If I have a change of heart, I will let you know.
