### ISSUE TITLE
How can I test this works? 

### ISSUE THREAD

**Issue by kareldeman** [StarPlayrX/Virtual-Multi-Mouse#2]
I am still a bit mystified how this works in the end. I have installed everything according to the instructions:

- My spinner is on device 0 and does work fine in games such as Arkanoid
- However, I cannot get the trackball to work in for example Centipide or Missile Command. I would expect the trackball to work there.

(note: these are MAME games by the way)

How does the system know it needs to use the trackball in Centipide and to use the spinner in Arkanoid? 

Some screenshots....

Here is a screenshot of my mm.log
<img width="530" alt="image" src="https://github.com/StarPlayrX/Virtual-Multi-Mouse/assets/17554220/f887e6b5-96d4-413a-af7b-5c7628858ba7">

And here is a screenshot of my multimouse.log
<img width="419" alt="image" src="https://github.com/StarPlayrX/Virtual-Multi-Mouse/assets/17554220/444aafa3-c017-4262-9947-ab0206b63add">

And here is screenshot of bottom of batocera.conf file
<img width="428" alt="image" src="https://github.com/StarPlayrX/Virtual-Multi-Mouse/assets/17554220/31dcf542-ecba-42f7-b458-3e8f9ca434c6">

And here is the version of Batocera
<img width="382" alt="image" src="https://github.com/StarPlayrX/Virtual-Multi-Mouse/assets/17554220/68850e86-c3d7-4a0d-85a5-619c07cf7f55">

**Comment by macOS26** [comment]
Looks like it is not combining this:
usb-Ultimarc U-Trak 6-mouse

I'll do some debugging.

**Comment by StarPlayrX** [comment]
I'm not having an issue with that latest branch off main on Batocera 37.  However I do not have the same hardware.

When you have time, send me the purchase links to your U-trak and Spin-trak. I'll get them in for testing to see where the breakdown is. Don't worry about the cost. I can resell them.

**Comment by kareldeman** [comment]
> Looks like it is not combining this: usb-Ultimarc U-Trak 6-mouse
> 
> I'll do some debugging.

Any updates? Thank you very much!

**Comment by macOS26** [comment]
Not at the moment. I need to sit down and review the code, flow, as it's been several months since I last touched the code and I found a more pressing issue that affects all users.

**Comment by macOS26** [comment]
Development has been discontinued. 

I decided to move on to native emulators and the ones I am choose for my hardware natively supports mice. 

These emulators are Stella, MAME and BigPEmu.

If I have a change of heart, I will let you know.
